[WIP] Depoly real env found issues fix
theopenlab/labkeeper pull request #112
Opened 2019-05-28 12:14 UTC by bzhaoopenstack

2019-05-29 01:11 UTC, wangxiyuan requested changes

2019-05-29 01:11 UTC, wangxiyuan commented on playbooks/prerequisites.yaml
> +        - python-setuptools
python3-setuptools should be added as well.

2019-05-29 01:26 UTC, huangtianhua approved these changes

2019-05-29 01:35 UTC, wangxiyuan commented
Let's wait a moment in order to fix all related bug in one PR.

2019-05-29 07:42 UTC, Yikun commented on playbooks/prerequisites.yaml
> +        - python3-setuptools
and `openstack` commands?

2019-05-29 07:49 UTC, wangxiyuan commented on openlabcmd/requirements.txt
>  enum;python_version=='2.7'
not related to this patch:  enum can be removed, since openlabcmd is only for py3 now.

2019-05-29 10:54 UTC, Yikun commented
recheck

2019-05-29 13:44 UTC, wangxiyuan commented
recheck

2019-05-30 01:20 UTC, bzhaoopenstack commented
recheck

2019-05-30 10:49 UTC, wangxiyuan approved these changes

2019-05-30 10:49 UTC, merged