Add upgrade command
theopenlab/labkeeper pull request #157
Opened 2019-06-18 08:55 UTC by wangxiyuan

This pr add openlab ha upgrade tool and doc

2019-06-18 12:10 UTC, Yikun requested changes

2019-06-18 12:10 UTC, Yikun commented on deploy.py
> +def list_changes(project, days):
nit: list-change

2019-06-18 12:10 UTC, Yikun commented on playbooks/upgrade-ha-deployment.yaml
> +        openlab ha node set `hostname` --maintain yes
Should we also reset the maintain status back to `no` after upgrade ?

2019-06-18 12:10 UTC, Yikun commented on playbooks/upgrade-ha-deployment.yaml
> +      shell: |
Should we consider to set the `set -e` to enable the error exit to do short exit when error happen.

2019-06-18 12:10 UTC, Yikun commented on ha_healthchecker/README.md
> +4. Once all services works as expect, command `./deploy.py openlab-ha upgrade-complete`. This command will set all nodes back to `up` status.
nit: Once all services **work** as expect

2019-06-18 12:10 UTC, Yikun commented on ha_healthchecker/README.md
> +3. Once `upgarde` action is done, operator should check the deployment to ensure every service works well. If not, operator should fix it by hand.
it seems not set back to `up` in implementation

2019-06-18 12:16 UTC, Yikun commented on ha_healthchecker/README.md
> +3. Once `upgarde` action is done, operator should check the deployment to ensure every service works well. If not, operator should fix it by hand.
upgrade

2019-06-18 12:28 UTC, wangxiyuan commented on deploy.py
> +def list_changes(project, days):
function name should use _

2019-06-19 01:17 UTC, Yikun commented on deploy.py
> +def list_changes(project, days):
I mean list_change, but I see you can the list_changes under list_change arg. So, I don't think it's necessary change.

[1] https://github.com/theopenlab/labkeeper/blob/acb1d02/deploy.py#L112

2019-06-19 01:17 UTC, Yikun approved these changes

2019-06-19 06:55 UTC, bzhaoopenstack approved these changes
Go for test

2019-06-19 06:56 UTC, merged